# actual_exp_phase_1
Script para analizar los csv que genera oTree con los datos del de prueba.

actualmente con "otree test experiment --export=bot_data.csv" debe generar los datos

In [1]:
import pandas as pd

In [2]:
actual_exp_phase_1 = pd.read_csv('bot_data.csv/actual_exp_phase_1.csv')

In [3]:
actual_exp_phase_1.head()

,participant.id_in_session,participant.code,participant.label,participant._is_bot,participant._index_in_pages,participant._max_page_index,participant._current_app_name,participant._current_page_name,participant.time_started_utc,participant.visited,...,player.jr_10,player.min_opp_punish_10,group.id_in_subsession,subsession.round_number,session.code,session.label,session.mturk_HITId,session.mturk_HITGroupId,session.comment,session.is_demo
0,1,6xfnu96p,NaN,0,39,1890,actual_exp_phase_1,WillingnessToJudgeFixedCost,2025-08-22 21:59:07.770517,1,...,1.0,NaN,1,1,gt17z5qr,NaN,NaN,NaN,NaN,1
1,2,gotyn0f3,NaN,0,0,1890,NaN,NaN,NaN,0,...,NaN,NaN,1,1,gt17z5qr,NaN,NaN,NaN,NaN,1
2,3,6g1y4hh9,NaN,0,0,1890,NaN,NaN,NaN,0,...,NaN,NaN,1,1,gt17z5qr,NaN,NaN,NaN,NaN,1
3,4,x7uvg44k,NaN,0,0,1890,NaN,NaN,NaN,0,...,NaN,NaN,1,1,gt17z5qr,NaN,NaN,NaN,NaN,1
4,5,ps0zwy13,NaN,0,0,1890,NaN,NaN,NaN,0,...,NaN,NaN,1,1,gt17z5qr,NaN,NaN,NaN,NaN,1

In [6]:
last_session_code = (
    actual_exp_phase_1
    .sort_values(by='participant.time_started_utc',ascending=False)
    ['session.code']
    .values
    [0]
)

In [23]:
(
    actual_exp_phase_1
    [actual_exp_phase_1['session.code']==last_session_code]
    [['participant.id_in_session', 'participant.code',
       'participant._is_bot', 'participant._current_app_name',
       'participant.payoff', 'player.payoff',
       'player.id_in_group',
       'player.topic_idx', 'player.treatment_idx',
       'subsession.round_number', 'session.code']]
    .sort_values(by=['subsession.round_number', 'participant.id_in_session'])
)

,participant.id_in_session,participant.code,participant._is_bot,participant._current_app_name,participant.payoff,player.payoff,player.id_in_group,player.topic_idx,player.treatment_idx,subsession.round_number,session.code
4320,1,5cl94pt9,1,actual_exp_phase_1,-4000.0,-1000.0,1,NaN,NaN,1,ub3c8t6z
4321,2,vcri5ypd,1,actual_exp_phase_1,-2000.0,-1000.0,2,NaN,NaN,1,ub3c8t6z
4322,3,8lxan0i6,1,actual_exp_phase_1,-5000.0,-2000.0,3,NaN,NaN,1,ub3c8t6z
4323,4,9kglgib7,1,actual_exp_phase_1,-1000.0,-1000.0,4,NaN,NaN,1,ub3c8t6z
4324,5,z3behsln,1,actual_exp_phase_1,-4000.0,1000.0,5,NaN,NaN,1,ub3c8t6z
...,...,...,...,...,...,...,...,...,...,...,...
6590,21,7uzc17of,1,actual_exp_phase_1,-3000.0,-2000.0,21,1.0,4.0,91,ub3c8t6z
6591,22,jy6h94m7,1,actual_exp_phase_1,0.0,-2000.0,22,2.0,6.0,91,ub3c8t6z
6592,23,j0gjp2s5,1,actual_exp_phase_1,-2000.0,-1000.0,23,6.0,0.0,91,ub3c8t6z
6593,24,ffw9prty,1,actual_exp_phase_1,-1000.0,0.0,24,4.0,1.0,91,ub3c8t6z
6594,25,usn2ahfv,1,actual_exp_phase_1,0.0,-2000.0,25,5.0,7.0,91,ub3c8t6z

In [ ]:
### Stage 2: player.topic_idx', 'player.treatment_idx', 'player.wtj',
"""'player.public_opinion', 'player.paid_cost_A', 'player.paid_cost_B',
       'player.expr_A_from_A', 'player.expr_A_from_B',
       'player.paid_round_stage2', 'player.stage2_payoff_points',
       'player.stage2_bonus_hit'"""

"'player.public_opinion', 'player.paid_cost_A', 'player.paid_cost_B',\n       'player.expr_A_from_A', 'player.expr_A_from_B',\n       'player.paid_round_stage2', 'player.stage2_payoff_points',\n       'player.stage2_bonus_hit'"