# actual_exp_phase_1
Script para analizar los csv que genera oTree con los datos del de prueba.

actualmente con "otree test experiment --export=bot_data.csv" debe generar los datos

In [1]:
import pandas as pd

In [2]:
actual_exp_phase_1 = pd.read_csv('bot_data.csv/actual_exp_phase_1.csv')

In [3]:
actual_exp_phase_1[actual_exp_phase_1['session.code'] == 'yvw8pit3']

,participant.id_in_session,participant.code,participant.label,participant._is_bot,participant._index_in_pages,participant._max_page_index,participant._current_app_name,participant._current_page_name,participant.time_started_utc,participant.visited,...,player.min_opp_punish_9,player.min_opp_punish_10,group.id_in_subsession,subsession.round_number,session.code,session.label,session.mturk_HITId,session.mturk_HITGroupId,session.comment,session.is_demo
4320,1,4m5kni0l,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.379537,1,...,3.0,2.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4321,2,b1lqe0lo,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.394881,1,...,8.0,9.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4322,3,xggq7l0q,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.400719,1,...,3.0,5.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4323,4,cy3wns4j,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.406361,1,...,8.0,0.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4324,5,ce23ubwb,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.411961,1,...,9.0,8.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4325,6,nzss55a1,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.417435,1,...,2.0,5.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4326,7,aab1c937,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.422895,1,...,2.0,6.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4327,8,1uy2zurz,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.428529,1,...,2.0,5.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4328,9,bd09z869,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.434123,1,...,9.0,2.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4329,10,7bx66fxe,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.439532,1,...,6.0,8.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4330,11,2qich0b3,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.445071,1,...,0.0,4.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4331,12,7c8kfrlr,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.450587,1,...,9.0,6.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4332,13,ocmn8q6c,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.456253,1,...,3.0,8.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4333,14,wvpqpkak,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.461615,1,...,2.0,6.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4334,15,y9u3b6gp,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.467104,1,...,7.0,3.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4335,16,z2lu7hxo,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.472619,1,...,1.0,2.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4336,17,j3dwc37a,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.478092,1,...,7.0,1.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4337,18,wymsfxp0,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.483558,1,...,4.0,0.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4338,19,k9k1nbz2,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.489056,1,...,3.0,4.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4339,20,em9bpj80,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.494642,1,...,8.0,3.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4340,21,7pl1dfj8,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.500124,1,...,8.0,0.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4341,22,xcwp0ne6,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.505470,1,...,8.0,6.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4342,23,p58vkx0o,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.510936,1,...,7.0,0.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4343,24,8unssb5f,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.516301,1,...,10.0,6.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4344,25,nncuc2ov,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.521802,1,...,4.0,2.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4345,26,ys89194z,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.527422,1,...,7.0,0.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4346,27,cpqddezt,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.532893,1,...,3.0,2.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4347,28,0vle94q9,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.538250,1,...,9.0,10.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4348,29,owzcpojs,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.543751,1,...,8.0,10.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0
4349,30,a47ii62n,NaN,1,15,14,actual_exp_phase_1,PaymentWaitPage,2025-10-03 01:52:18.549566,1,...,2.0,10.0,1,1,yvw8pit3,NaN,NaN,NaN,NaN,0

In [ ]:
(
    actual_exp_phase_1
    .sort_values(by='participant.time_started_utc',ascending=False)
    [['session.code','participant.code','participant.label','participant.time_started_utc', 'participant.payoff']]
)

,session.code,participant.code,participant.label,participant.time_started_utc,participant.payoff
4349,yvw8pit3,a47ii62n,NaN,2025-10-03 01:52:18.549566,-4.0
4348,yvw8pit3,owzcpojs,NaN,2025-10-03 01:52:18.543751,-1.0
4347,yvw8pit3,0vle94q9,NaN,2025-10-03 01:52:18.538250,-1.0
4346,yvw8pit3,cpqddezt,NaN,2025-10-03 01:52:18.532893,0.0
4345,yvw8pit3,ys89194z,NaN,2025-10-03 01:52:18.527422,0.0
...,...,...,...,...,...
4307,snh6yxi2,slsw90xw,NaN,NaN,0.0
4312,snh6yxi2,ft1blsxw,NaN,NaN,0.0
4313,snh6yxi2,slsw90xw,NaN,NaN,0.0
4318,snh6yxi2,ft1blsxw,NaN,NaN,0.0
4319,snh6yxi2,slsw90xw,NaN,NaN,0.0