# actual_exp_phase_1
Script para analizar los csv que genera oTree con los datos del de prueba.

actualmente con "otree test experiment --export=bot_data.csv" debe generar los datos

In [1]:
import pandas as pd

In [2]:
actual_exp_phase_1 = pd.read_csv('bot_data.csv/actual_exp_phase_1.csv')

/var/folders/p_/v1md7gns6zb22p13_7_zlkwm0000gp/T/ipykernel_68512/2391889678.py:1: DtypeWarning: Columns (20,23,24,33,41,42,43,44,45,46,47,48,49,50,52,54,55,56,60) have mixed types. Specify dtype option on import or set low_memory=False.
  actual_exp_phase_1 = pd.read_csv('bot_data.csv/actual_exp_phase_1.csv')

In [5]:
actual_exp_phase_1.head()

,participant.id_in_session,participant.code,participant.label,participant._is_bot,participant._index_in_pages,participant._max_page_index,participant._current_app_name,participant._current_page_name,participant.time_started_utc,participant.visited,...,player.min_opp_punish_9,player.min_opp_punish_10,group.id_in_subsession,subsession.round_number,session.code,session.label,session.mturk_HITId,session.mturk_HITGroupId,session.comment,session.is_demo
0,1,83q3udgo,NaN,0,4,1911,actual_exp_phase_1,Practice_WTJ,2025-09-30 21:11:45.968334,1,...,NaN,NaN,1,1,q70hgd1h,NaN,NaN,NaN,NaN,1
1,2,2ky7pz4r,NaN,0,2,1911,actual_exp_phase_1,Practice_BinaryTopic,2025-09-30 21:20:30.351064,1,...,NaN,NaN,1,1,q70hgd1h,NaN,NaN,NaN,NaN,1
2,3,wurckkjt,NaN,0,0,1911,NaN,NaN,NaN,0,...,NaN,NaN,1,1,q70hgd1h,NaN,NaN,NaN,NaN,1
3,4,ab7ake53,NaN,0,0,1911,NaN,NaN,NaN,0,...,NaN,NaN,1,1,q70hgd1h,NaN,NaN,NaN,NaN,1
4,5,4f0ldv2g,NaN,0,0,1911,NaN,NaN,NaN,0,...,NaN,NaN,1,1,q70hgd1h,NaN,NaN,NaN,NaN,1

In [7]:
(
    actual_exp_phase_1
    .sort_values(by='participant.time_started_utc',ascending=False)
    [['session.code','subsession.round_number','participant.code','participant.label','participant.time_started_utc', 'participant.payoff', 'player.payoff']]
)

,session.code,subsession.round_number,participant.code,participant.label,participant.time_started_utc,participant.payoff,player.payoff
47042,saovopm3,1,mlqyrxhy,NaN,2025-10-23 03:15:55.152194,2000.0,2000.0
47041,saovopm3,1,0iailqld,NaN,2025-10-23 03:15:55.147040,2000.0,2000.0
47040,saovopm3,1,8eqdeetm,NaN,2025-10-23 03:15:55.141874,2000.0,2000.0
47039,saovopm3,1,x00bsezd,NaN,2025-10-23 03:15:55.136567,1000.0,1000.0
47038,saovopm3,1,cqbpoc9u,NaN,2025-10-23 03:15:55.131258,1000.0,1000.0
...,...,...,...,...,...,...,...
47023,8v8ygjw1,91,lp6tah1v,NaN,NaN,2000.0,0.0
47024,8v8ygjw1,91,j0bf75u5,NaN,NaN,2000.0,0.0
47025,8v8ygjw1,91,djoywkr1,NaN,NaN,2000.0,0.0
47026,8v8ygjw1,91,s2jc0050,NaN,NaN,2000.0,0.0
47027,8v8ygjw1,91,qj8wrug3,NaN,NaN,2000.0,0.0

In [13]:
### Stage 2: player.topic_idx', 'player.treatment_idx', 'player.wtj',
"""'player.public_opinion', 'player.paid_cost_A', 'player.paid_cost_B',
       'player.expr_A_from_A', 'player.expr_A_from_B',
       'player.paid_round_stage2', 'player.stage2_payoff_points',
       'player.stage2_bonus_hit'"""

"'player.public_opinion', 'player.paid_cost_A', 'player.paid_cost_B',\n       'player.expr_A_from_A', 'player.expr_A_from_B',\n       'player.paid_round_stage2', 'player.stage2_payoff_points',\n       'player.stage2_bonus_hit'"

In [11]:
actual_exp_phase_1[actual_exp_phase_1['session.code']=='saovopm3']

,participant.id_in_session,participant.code,participant.label,participant._is_bot,participant._index_in_pages,participant._max_page_index,participant._current_app_name,participant._current_page_name,participant.time_started_utc,participant.visited,...,player.min_opp_punish_9,player.min_opp_punish_10,group.id_in_subsession,subsession.round_number,session.code,session.label,session.mturk_HITId,session.mturk_HITGroupId,session.comment,session.is_demo
47028,1,yrtory9s,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.056314,1,...,8.0,2.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47029,2,sdpkau2q,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.076226,1,...,5.0,3.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47030,3,chhzhsn6,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.083249,1,...,9.0,5.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47031,4,u9r1bfhj,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.089409,1,...,7.0,9.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47032,5,0meuwe8z,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.096755,1,...,5.0,4.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47033,6,ogr8tboj,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.103896,1,...,8.0,8.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47034,7,ybmnoc6b,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.109511,1,...,8.0,2.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47035,8,dn4rb6zj,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.115023,1,...,2.0,5.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47036,9,qn3hb55p,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.120518,1,...,9.0,2.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47037,10,bez11vhe,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.125879,1,...,1.0,9.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47038,11,cqbpoc9u,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.131258,1,...,8.0,1.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47039,12,x00bsezd,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.136567,1,...,8.0,10.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47040,13,8eqdeetm,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.141874,1,...,6.0,3.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47041,14,0iailqld,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.147040,1,...,10.0,10.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0
47042,15,mlqyrxhy,NaN,1,19,18,actual_exp_phase_1,PaymentWaitPage,2025-10-23 03:15:55.152194,1,...,6.0,8.0,1,1,saovopm3,NaN,NaN,NaN,NaN,0